# Generated by Django 5.0.4 on 2024-04-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonfeedback',
            name='HomeWorkCheck',
            field=models.BooleanField(default=False, verbose_name='Проверка ДЗ'),
        ),
    ]
