# Generated by Django 5.0.4 on 2024-04-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_lessonfeedback_homeworkcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(blank=True, null=True, verbose_name='Группа')),
                ('monday', models.BooleanField(default=False, verbose_name='Понедельник')),
                ('mondayTime', models.TimeField(blank=True, null=True, verbose_name='Время занятий в понедельник')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Вторник')),
                ('tuesdayTime', models.TimeField(blank=True, null=True, verbose_name='Время занятий в вторник')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Среда')),
                ('wednesdayTime', models.TimeField(blank=True, null=True, verbose_name='Время занятий в Среду')),
                ('thursday', models.BooleanField(default=False, verbose_name='Четверг')),
                ('thursdayTime', models.TimeField(blank=True, null=True, verbose_name='Время занятий в понедельник')),
                ('friday', models.BooleanField(default=False, verbose_name='Пятница')),
                ('fridayTime', models.TimeField(blank=True, null=True, verbose_name='Время занятий в пятницу')),
                ('saturday', models.BooleanField(default=False, verbose_name='Суббота')),
                ('saturdayTime', models.TimeField(blank=True, null=True, verbose_name='Время занятий в субботу')),
                ('sunday', models.BooleanField(default=False, verbose_name='Воскресенье')),
                ('sundayTime', models.TimeField(blank=True, null=True, verbose_name='Время занятий в воскресенье')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
