# Generated by Django 5.0.4 on 2024-04-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_lesson_description_alter_lesson_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='fridayTimeFinal',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания занятий в пятницу'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='mondayTimeFinal',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания занятий в понедельник'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturdayTimeFinal',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания занятий в субботу'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sundayTimeFinal',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания занятий в воскресенье'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursdayTimeFinal',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания занятий в четверг'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesdayTimeFinal',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания занятий во вторник'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesdayTimeFinal',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания занятий в среду'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursdayTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Время занятий в четверг'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesdayTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Время занятий во вторник'),
        ),
    ]
